# -*- coding: utf-8 -*-
"""Read file content from AWS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z39snlU3baJGCk_ib70WQt8c-Rc_ADpF
"""

import boto3

# AWS 계정 정보 및 버킷 이름 설정
aws_access_key = ''
aws_secret_key = ''
bucket_name = ''
file_key = 'label1.txt'  # 파일의 경로 및 이름

# AWS S3 클라이언트 생성
s3 = boto3.client(
    's3',
    aws_access_key_id=aws_access_key,
    aws_secret_access_key=aws_secret_key
)

# 파일 읽기
try:
    response = s3.get_object(Bucket=bucket_name, Key=file_key)
    content = response['Body'].read().decode('utf-8')  # 파일 내용 읽어오기

    # 파일 내용 출력
    print("File Contents:")
    print(content)

    # 읽어온 값에 따라 조건문 실행
    value = int(content.strip())  # 문자열로 읽어온 값을 정수로 변환
    if value == 0:
        print("정상입니다")
    else:
        print("피싱입니다")

except Exception as e:
    print("Error reading file:", e)

!pip install boto3